name: magveto
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_riverpod: ^2.4.5
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  riverpod: ^2.4.5
  riverpod_generator: ^2.3.5

dev_dependencies:
  build_runner: ^2.0.0
  custom_lint: ^0.5.6
  flutter_lints: ^3.0.1

  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  go_router_builder: ^2.3.4
  json_serializable: ^6.7.1
  riverpod_lint: ^2.3.3

flutter:
  assets:
    - assets/icons/
    - assets/images/
    - assets/logo/

  uses-material-design: true
