name: magveto_web
description: Magveto web is a catholic website 
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_riverpod: ^2.4.5
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  intl: ^0.18.1
  lorem_ipsum: ^0.0.3
  riverpod: ^2.4.5
  riverpod_generator: ^2.3.5
  smooth_page_indicator: ^1.1.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  build_runner: ^2.0.0
  custom_lint: ^0.5.6
  flutter_lints: ^3.0.1

  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  go_router_builder: ^2.3.4
  json_serializable: ^6.7.1
  riverpod_lint: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/logo/

  fonts:
    - family: 'Cabin Sketch'
      fonts:
        - asset: assets/fonts/CabinSketch-Regular.ttf
        - asset: assets/fonts/CabinSketch-Bold.ttf
          weight: 700
